version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  say-goodbye:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say farewell"
          command: "echo So long!"

  turn-off-microphone:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Turn off microphone"
          command: "echo We should be done saying things..."

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  default_workflow:
    jobs:
      - say-hello
      - turn-off-microphone:
          requires:
            - say-hello
