version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  say-goodbye:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say farewell"
          command: "echo So long!"

  turn-off-microphone:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Turn off microphone"
          command: "echo We should be done saying things..."

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  main_workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              only:
                - main
      - turn-off-microphone:
          requires:
            - say-hello

  alternate_workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              ignore:
                - main
      - say-goodbye:
        requires:
          - say-hello
      - turn-off-microphone:
          requires:
            - say-goodbye
